name: deploy website

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-node@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0

      - name: Build
        run: hugo --cleanDestinationDir

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pass }}
          local-dir: ./public/

      # For publishing on Github Pages:

      # - name: add nojekyll
      #   run: touch ./docs/public/.nojekyll
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v2.4.0
      #   with:
      #     emptyCommits: false
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: ./docs/public
